#   ██████ ▄▄▄█████▓ ▄▄▄       ██▀███  ▄▄▄█████▓
# ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██ ▒ ██▒▓  ██▒ ▓▒
# ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▓██ ░▄█ ▒▒ ▓██░ ▒░
#   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ▒██▀▀█▄  ░ ▓██▓ ░
# ▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░██▓ ▒██▒  ▒██▒ ░
# ▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░░ ▒▓ ░▒▓░  ▒ ░░
# ░ ░▒  ░ ░    ░      ▒   ▒▒ ░  ░▒ ░ ▒░    ░
# ░  ░  ░    ░        ░   ▒     ░░   ░   ░
#       ░                 ░  ░   ░
#


exec-once = hyprpaper
exec-once = hypridle
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = nm-applet
exec-once = waybar && dunst
exec-once = clipse -listen
exec-once = [workspace special:claude silent] alacritty --class claude-code -e claude
exec = ~/.local/bin/battery_chargin.sh 
exec = ~/.local/bin/battery_low.sh
exec = ~/.local/bin/battery_high.sh && ~/.local/bin/wifi_alert.sh
