#   ██████ ▄▄▄█████▓ ▄▄▄       ██▀███  ▄▄▄█████▓
# ▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██ ▒ ██▒▓  ██▒ ▓▒
# ░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▓██ ░▄█ ▒▒ ▓██░ ▒░
#   ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ▒██▀▀█▄  ░ ▓██▓ ░
# ▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░██▓ ▒██▒  ▒██▒ ░
# ▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░░ ▒▓ ░▒▓░  ▒ ░░
# ░ ░▒  ░ ░    ░      ▒   ▒▒ ░  ░▒ ░ ▒░    ░
# ░  ░  ░    ░        ░   ▒     ░░   ░   ░
#       ░                 ░  ░   ░
#


# Start workspace 1 in float mode
exec-once = mkdir -p /tmp/hypr-float-cache/state && touch /tmp/hypr-float-cache/state/ws-1 && python3 ~/.config/hypr/scripts/float-mode-listener.py

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = awww-daemon && sleep 0.5 && awww img "$(readlink -f ~/.config/hypr/current_wallpaper 2>/dev/null || echo ~/Pictures/wallpapers/wallhaven-9d13wx.jpg)" --transition-type any --transition-fps 60
exec-once = hyprlock
exec-once = hypridle
exec-once = wayland-pipewire-idle-inhibit
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = nmcli radio wifi on
exec-once = nm-applet
exec-once = waybar
exec-once = mako
exec-once = wl-paste --watch cliphist store
# exec-once = env -u CLAUDECODE alacritty --class claude-code -e /home/christian/.local/bin/claude --resume
exec = ~/.local/bin/battery_chargin.sh 
exec = ~/.local/bin/battery_low.sh
exec = ~/.local/bin/battery_high.sh && ~/.local/bin/wifi_alert.sh
