#   ▄████ ▓█████  ███▄    █ ▓█████  ██▀███  ▓█████ ▄▄▄       ██▓    
#  ██▒ ▀█▒▓█   ▀  ██ ▀█   █ ▓█   ▀ ▓██ ▒ ██▒▓█   ▀▒████▄    ▓██▒    
# ▒██░▄▄▄░▒███   ▓██  ▀█ ██▒▒███   ▓██ ░▄█ ▒▒███  ▒██  ▀█▄  ▒██░    
# ░▓█  ██▓▒▓█  ▄ ▓██▒  ▐▌██▒▒▓█  ▄ ▒██▀▀█▄  ▒▓█  ▄░██▄▄▄▄██ ▒██░    
# ░▒▓███▀▒░▒████▒▒██░   ▓██░░▒████▒░██▓ ▒██▒░▒████▒▓█   ▓██▒░██████▒
#  ░▒   ▒ ░░ ▒░ ░░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒▓ ░▒▓░░░ ▒░ ░▒▒   ▓▒█░░ ▒░▓  ░
#   ░   ░  ░ ░  ░░ ░░   ░ ▒░ ░ ░  ░  ░▒ ░ ▒░ ░ ░  ░ ▒   ▒▒ ░░ ░ ▒  ░
# ░ ░   ░    ░      ░   ░ ░    ░     ░░   ░    ░    ░   ▒     ░ ░   
#       ░    ░  ░         ░    ░  ░   ░        ░  ░     ░  ░    ░  ░
#                                                                   

source = ~/.config/hypr/themes/mocha.conf
source = ~/.config/hypr/colors.conf

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 3
    col.active_border = rgb(a5adcb)
    col.inactive_border = rgb(24273A)
    resize_on_border = false
    layout = master
}

master {
    new_status = slave
    mfact = 0.55
}
