
[window]
opacity = 0.65
padding = { x = 3, y = 3 }
decorations = "None"

[cursor.style]
shape = "Block"
blinking = "On"

[keyboard]
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
