title	Arch Linux (CLI)
linux	/vmlinuz-linux-t2
initrd	/initramfs-linux-t2.img
options	root=/dev/nvme0n1p4 rw brcmfmac.feature_disable=0x82000 mem_sleep_default=deep intel_iommu=on iommu=pt pcie_ports=compat pm_async=off systemd.unit=multi-user.target modprobe.blacklist=amdgpu
